engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 200
  eslint:
    enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - src/**/*
exclude_paths:
- test/**/*
- utils/**/*
- public/**/*
- src/**/*.test.js
- src/**/*.test.jsx
