language: node_js
addons:
  code_climate:
node_js:
  - "6"

install: yarn install
script: yarn run test
after_success:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
