language: node_js
node_js:
  - "6"

install: npm install
before_script: utils/lint-files-changed.sh
script: npm run test:phantomjs
after_success: cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage